### ISSUE TITLE
Specific IBAN has different result (web-gui/rest-service)

### ISSUE THREAD

**Issue by dirk-moll** [apilayer/goiban-service#33]
Hi, 

using the rest API returns another result than using the web front end for a specific IBAN.

IBAN: DE92100179971115761798
Web GUI returns it with bank information. 
Rest returns it without bank information. 
 
https://openiban.com/validate/DE92100179971115761798

Please let me know if you are going to fix that and when you have this fixed. 

Regards
Dirk

**Comment by fourcube** [comment]
Hi Dirk,

if you want to retrieve the bank data, you can use the "getBIC" parameter. For example:

https://openiban.com/validate/DE92100179971115761798?getBIC=true

**Comment by dirk-moll** [comment]
OKi, that works. Thanx, did not see that parameter.
